  {id:'role',tag:'PORTFOLIO',title:'Portfolio Role Worksheet',desc:'Define the job of each holding and test whether it adds a distinct exposure.',fields:[['ticker','Ticker / Fund'],['weight','Portfolio Weight %'],['role','Role: Core / Diversifier / Tilt'],['adds','What does it add?'],['overlap','Known overlap / duplication'],['notes','Evidence & notes','textarea']],formula:'Holding contribution = Allocation weight × Holding return',legend:[['w','portfolio allocation as a decimal'],['r','holding return as a decimal'],['C','contribution to portfolio return; C = w × r']]},
  {id:'financials',tag:'COMPANY ANALYSIS',title:'Financial Statement Worksheet',desc:'Connect income, balance sheet and cash-flow evidence.',fields:[['ticker','Ticker'],['revenue','Revenue'],['netIncome','Net income'],['ocf','Operating cash flow'],['capex','Capital expenditures'],['cash','Cash'],['debt','Total debt'],['notes','What changed and why?','textarea']],formula:'FCF = Operating Cash Flow − Capital Expenditures',legend:[['FCF','free cash flow'],['OCF','cash generated by operations'],['CapEx','cash spent on long-lived productive assets']]},
  {id:'roic',tag:'QUALITY',title:'ROIC & Capital Quality Worksheet',desc:'Estimate returns on invested capital and compare them with the cost of capital.',fields:[['nopat','NOPAT'],['invested','Invested Capital'],['roic','ROIC %'],['wacc','Estimated WACC %'],['notes','Interpretation / evidence','textarea']],formula:'ROIC = NOPAT ÷ Invested Capital',legend:[['NOPAT','net operating profit after tax'],['Invested Capital','capital committed to operations'],['WACC','weighted average cost of capital'],['Spread','ROIC − WACC; a positive spread indicates returns above the estimated capital cost']]},
  {id:'valuation',tag:'VALUATION',title:'Valuation Worksheet',desc:'Organize earnings, cash flow and price-based valuation evidence.',fields:[['price','Share price'],['eps','Earnings per share'],['fcfps','FCF per share'],['normalized','Normalized EPS'],['notes','Valuation evidence / comparison','textarea']],formula:'P/E = Price ÷ EPS    |    FCF Yield = FCF per Share ÷ Price',legend:[['P/E','price-to-earnings multiple'],['EPS','earnings per share'],['FCF Yield','free cash flow generated per dollar of market price']]},
  {id:'dcf',tag:'INTRINSIC VALUE',title:'DCF Worksheet',desc:'Estimate present value from cash-flow assumptions and document every assumption.',fields:[['fcf','Starting FCF'],['growth','Growth rate %'],['discount','Discount rate %'],['terminal','Terminal growth %'],['years','Forecast years'],['netDebt','Net debt'],['shares','Diluted shares'],['notes','Assumptions / evidence','textarea']],formula:'PV = FCFₜ ÷ (1 + r)ᵗ    |    Terminal Value = FCFₙ₊₁ ÷ (r − g)',legend:[['FCFₜ','free cash flow in year t'],['r','discount rate'],['t','forecast year'],['g','terminal growth rate'],['Terminal Value','estimated value of cash flows beyond the explicit forecast'],['Equity Value','enterprise value less net debt'],['Per Share Value','equity value ÷ diluted shares']]},
  {id:'mos',tag:'VALUATION',title:'Margin of Safety Worksheet',desc:'Compare estimated value with market price without hiding the assumptions behind the estimate.',fields:[['value','Estimated intrinsic value'],['price','Current market price'],['mos','Margin of Safety %'],['notes','What could make the value estimate wrong?','textarea']],formula:'Margin of Safety = (Estimated Value − Price) ÷ Estimated Value',legend:[['Estimated Value','value produced by the chosen valuation method and assumptions'],['Price','current market price'],['MOS','percentage discount of price to the estimate; it does not guarantee against loss']]},
  {id:'thesis',tag:'THESIS',title:'Investment Thesis Worksheet',desc:'Turn research into a falsifiable investment argument.',fields:[['ticker','Ticker / Security'],['thesis','Core thesis','textarea'],['supports','Evidence supporting the thesis','textarea'],['challenges','Evidence challenging the thesis','textarea'],['risks','Material risks','textarea'],['change','What would change my view?','textarea']],formula:'Thesis test = Evidence → Interpretation → Implication',legend:[['Evidence','observable financial, market or fund data'],['Interpretation','what the evidence suggests'],['Implication','why that matters to the investment thesis']]},
  {id:'etf',tag:'FUND ANALYSIS',title:'ETF Analysis Worksheet',desc:'Evaluate what a fund owns, how it behaves and what job it performs.',fields:[['ticker','ETF ticker'],['expense','Expense ratio %'],['holdings','Holdings count'],['top10','Top-10 weight %'],['benchmark','Benchmark'],['factor','Factor / style exposure'],['overlap','Portfolio overlap %'],['role','Portfolio role'],['notes','Evidence & interpretation','textarea']],formula:'Weighted overlap = Σ min(Fund A weightᵢ, Fund B weightᵢ)',legend:[['i','a security held by both funds'],['weightᵢ','security weight within each fund'],['Weighted overlap','shared portfolio weight based on actual underlying holdings']]},
  {id:'review',tag:'PORTFOLIO REVIEW',title:'Portfolio Review Worksheet',desc:'Review performance, contribution, market evidence and whether the thesis changed.',fields:[['period','Review period'],['return','Portfolio return %'],['driver','Largest performance driver'],['macro','Relevant macro evidence','textarea'],['micro','Relevant security / fund evidence','textarea'],['changed','Did the thesis change? Why?','textarea'],['actions','Monitoring items','textarea']],formula:'Portfolio return ≈ Σ (Holding weight × Holding return)',legend:[['Holding weight','portfolio allocation during the measured period'],['Holding return','security or fund return during the period'],['Contribution','the portion of total portfolio return associated with that holding']]},
  {id:'overlap',tag:'PORTFOLIO',title:'Diversification & Overlap Worksheet',desc:'Separate ticker count from true underlying diversification.',fields:[['fundA','Fund A'],['fundB','Fund B'],['shared','Shared holdings'],['weighted','Weighted overlap %'],['distinct','What distinct exposure does each add?','textarea'],['notes','Interpretation','textarea']],formula:'Weighted overlap = Σ min(wAᵢ, wBᵢ)',legend:[['wAᵢ','weight of shared security i in Fund A'],['wBᵢ','weight of shared security i in Fund B'],['Σ','sum across securities held by both funds']]}
 ];
 const key='pt_saved_worksheets_v1';
 const load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
 const save=x=>localStorage.setItem(key,JSON.stringify(x));
 window.pt175LearnPage=function(page,btn){
   if(page!=='worksheets')return;
   document.querySelectorAll('.pt170-learnpage').forEach(x=>x.classList.remove('active'));
   document.getElementById('pt175Worksheets')?.classList.add('active');
   document.querySelectorAll('.pt170-tabs>button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');
   renderList();
 };
 function renderList(){
   const list=document.getElementById('pt175WorksheetList'), editor=document.getElementById('pt175WorksheetEditor'); if(!list)return;
   const head=document.querySelector('#pt175Worksheets .pt175-head'); if(head) head.style.display='';
   editor.style.display='none'; list.style.display='';
   const saved=load();
   const workspaces=[
    {id:'company',tag:'COMPANY ANALYSIS',title:'Analyze a Company',desc:'Move from financial evidence to business quality, valuation and a documented investment thesis.',flow:'Financial Statements → ROIC & Capital Quality → Valuation → DCF → Margin of Safety → Investment Thesis',ids:['financials','roic','valuation','dcf','mos','thesis']},
    {id:'fund',tag:'FUND & ETF ANALYSIS',title:'Analyze a Fund',desc:'Understand what a fund owns, what exposure it adds and the role it should play in a portfolio.',flow:'ETF Analysis → Portfolio Role',ids:['etf','role']},
    {id:'portfolio',tag:'PORTFOLIO ANALYSIS',title:'Review a Portfolio',desc:'Look through the holdings, identify overlap and concentration, then document what actually needs attention.',flow:'Diversification & Overlap → Portfolio Review',ids:['overlap','review']}
   ];
   list.innerHTML=`<div class="pt263-workspaces">${workspaces.map(w=>`<button class="pt263-workspace" type="button" onclick="pt263Workspace('${w.id}')"><small>${w.tag}</small><h3>${w.title}</h3><p>${w.desc}</p><span>Open workspace →</span></button>`).join('')}</div>`;
 }
 window.pt263Workspace=function(id){
   const groups={
    company:{tag:'COMPANY ANALYSIS',title:'Analyze a Company',flow:'Financial Evidence → Quality → Valuation → Thesis',ids:['financials','roic','valuation','dcf','mos','thesis']},
    fund:{tag:'FUND & ETF ANALYSIS',title:'Analyze a Fund',flow:'Fund Evidence → Exposure → Portfolio Role',ids:['etf','role']},
    portfolio:{tag:'PORTFOLIO ANALYSIS',title:'Review a Portfolio',flow:'Look-Through → Diversification → Review',ids:['overlap','review']}
   };
   const g=groups[id], list=document.getElementById('pt175WorksheetList'); if(!g||!list)return;
   const head=document.querySelector('#pt175Worksheets .pt175-head'); if(head) head.style.display='none';
   const saved=load();
   list.innerHTML=`<div class="pt263-workspace-head"><button class="pt263-back" type="button" onclick="pt175Back()">← All workspaces</button><div class="eyebrow">${g.tag}</div><h2>${g.title}</h2><div class="pt263-flow">${g.flow}</div></div>${g.ids.map(id=>{const d=defs.find(x=>x.id===id),n=saved.filter(x=>x.type===id).length;return `<div class="pt175-card" onclick="pt175Open('${id}')"><small>${d.tag}</small><h3>${d.title}</h3><p>${d.desc}</p><span class="pt175-open">Open worksheet →</span>${n?`<div class="pt175-saved">${n} saved ${n===1?'worksheet':'worksheets'}</div>`:''}</div>`}).join('')}`;
 };
 window.pt175Open=function(id,recordId){
   const d=defs.find(x=>x.id===id);if(!d)return;const list=document.getElementById('pt175WorksheetList'), ed=document.getElementById('pt175WorksheetEditor');
   const rec=recordId?load().find(x=>x.id===recordId):null;list.style.display='none';ed.style.display='block';
   ed.innerHTML=`<button class="pt175-btn" onclick="pt175Back()">← Worksheets</button><div class="pt175-editor" data-type="${id}" data-record="${rec?.id||''}"><div class="eyebrow">${d.tag}</div><h2>${d.title}</h2><p>${d.desc}</p><h3>Inputs & Evidence</h3><div class="pt175-grid">${d.fields.map(f=>`<div class="pt175-field"><label>${f[1]}</label>${f[2]==='textarea'?`<textarea data-field="${f[0]}">${rec?.values?.[f[0]]||''}</textarea>`:`<input data-field="${f[0]}" value="${rec?.values?.[f[0]]||''}">`}</div>`).join('')}</div><h3>Formula Reference</h3><div class="pt175-formula"><code>${d.formula}</code><div class="pt175-legend">${d.legend.map(x=>`<b>${x[0]}</b><span>${x[1]}</span>`).join('')}</div></div><h3>Interpretation</h3><div class="pt175-field"><textarea data-field="interpretation" placeholder="What does the evidence mean?">${rec?.values?.interpretation||''}</textarea></div><h3>Conclusion</h3><div class="pt175-field"><textarea data-field="conclusion" placeholder="Summarize what you learned and what should be monitored.">${rec?.values?.conclusion||''}</textarea></div><div class="pt175-actions"><button class="pt175-btn primary" onclick="pt175Save()">Save worksheet</button><button class="pt175-btn" onclick="pt175Back()">Close</button></div><div id="pt175SaveMsg" class="pt175-saved">${rec?`Last saved ${new Date(rec.savedAt).toLocaleString()}`:''}</div></div>`;
 }
 window.pt175Save=function(){
   const ed=document.querySelector('#pt175WorksheetEditor .pt175-editor');if(!ed)return;const values={};ed.querySelectorAll('[data-field]').forEach(x=>values[x.dataset.field]=x.value);
   let rows=load(), id=ed.dataset.record||('ws_'+Date.now()), row={id,type:ed.dataset.type,values,savedAt:new Date().toISOString()};
   const i=rows.findIndex(x=>x.id===id);if(i>=0)rows[i]=row;else rows.unshift(row);save(rows);ed.dataset.record=id;
   document.getElementById('pt175SaveMsg').textContent='Saved to My Worksheets · '+new Date().toLocaleString();
 };
 window.pt175Back=function(){document.getElementById('pt175WorksheetEditor').style.display='none';renderList()};
 // Make worksheet tab work even though original top-level function only knows 3 views.
 document.addEventListener('click',e=>{const b=e.target.closest('.pt170-tab');if(b&&(b.textContent||'').trim()==='Worksheets'){e.preventDefault();pt175LearnPage('worksheets',b)}});
})();


/* ===== ORIGINAL SCRIPT BLOCK SEPARATOR ===== */


(function(){
  function wire(){
    const tabs=[...document.querySelectorAll('.pt170-tabs>button')];
    const ws=tabs.find(b=>(b.textContent||'').trim()==='Worksheets');
    if(!ws)return;
    ws.onclick=function(e){
      e.preventDefault();
      document.querySelectorAll('.pt170-learnpage').forEach(x=>x.classList.remove('active'));
      const page=document.getElementById('pt175Worksheets');
      if(page)page.classList.add('active');
      tabs.forEach(x=>x.classList.remove('active'));
      ws.classList.add('active');
      if(typeof renderList==='function')renderList();
      else if(typeof window.pt175LearnPage==='function')window.pt175LearnPage('worksheets',ws);
      window.scrollTo({top:document.querySelector('.pt170-tabs')?.getBoundingClientRect().top + window.scrollY - 110 || 0,behavior:'auto'});
    };
  }
  setTimeout(wire,30);
})();


/* ===== ORIGINAL SCRIPT BLOCK SEPARATOR ===== */


(function(){
 const BASE='https://ngsdgtglfpsnylduivzz.supabase.co/functions/v1';
 const periods=[['w1','1W'],['m1','1M'],['m3','3M'],['m6','6M'],['ytd','YTD'],['y1','1Y']];
 const numberOrNull=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
 function normalize(x){
   const numberOrNull=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
   const out={w1:null,m1:null,m3:null,m6:null,ytd:null,y1:null};
   const assign=(path,obj)=>{
     const v=numberOrNull(obj?.portfolioReturnEstimatePct);
     if(v===null)return;
     const p=path.toLowerCase().replace(/[^a-z0-9]/g,'');
     if(/oneweek|1week|1w/.test(p))out.w1=v;
     else if(/onemonth|1month|1m/.test(p))out.m1=v;
     else if(/threemonth|3month|3m/.test(p))out.m3=v;
     else if(/sixmonth|6month|6m/.test(p))out.m6=v;
     else if(/yeartodate|ytd/.test(p))out.ytd=v;
     else if(/oneyear|1year|1y/.test(p))out.y1=v;
   };
   const walk=(node,path='',depth=0)=>{
     if(!node||typeof node!=='object'||depth>7)return;
     assign(path,node);
     if(Array.isArray(node))node.forEach((v,i)=>walk(v,`${path}.${i}`,depth+1));
     else for(const [k,v] of Object.entries(node))if(v&&typeof v==='object')walk(v,path?`${path}.${k}`:k,depth+1);
   };
   walk(x);
   return out;
 }
 function render(p,caption){
   return `<div class="pt180-perf"><div class="pt180-grid">${periods.map(([k,l])=>`<div class="pt180-cell"><small>${l}</small><b class="${cls(p[k])}">${fmt(p[k])}</b></div>`).join('')}</div><div class="pt180-caption">${caption}</div></div>`;
 }
 async function call(fn,body){
   try{
    const headers={'Content-Type':'application/json'};
    if(window.ptSupabase?.auth){const {data}=await window.ptSupabase.auth.getSession();const token=data?.session?.access_token;if(token)headers.Authorization='Bearer '+token}
    const controller=new AbortController();
