marketcap:{level:"INVESTING 101",title:"Market Cap & Portfolio Weight",body:`<p><b>Market capitalization</b> is a company's share price multiplied by shares outstanding. In a market-cap-weighted index, larger companies receive larger weights.</p><h4>Why this matters inside an ETF</h4><p>A fund can own thousands of companies and still have a meaningful share of its assets concentrated in its largest holdings. Holdings count measures breadth; top-holdings weight measures how evenly that breadth is distributed.</p><h4>Effective exposure</h4><p>If an ETF is 60% of your portfolio and a company is 6% of that ETF, the ETF contributes about 3.6 percentage points of portfolio exposure to that company before considering any other funds that also own it.</p><h4>Portfolio Thesis takeaway</h4><p>Broad ownership and equal ownership are different things. Always pair holdings count with concentration.</p>`},
factors:{level:"PORTFOLIO CONSTRUCTION",title:"Factor Tilts",body:`<p>A factor tilt deliberately changes the weights the broad market would otherwise assign. Common examples include <b>size</b>, <b>value</b>, <b>profitability</b>, momentum and investment.</p><h4>What a tilt actually does</h4><p>Adding a small/value fund does not simply add more stocks. It gives selected smaller and cheaper companies more influence than they receive in a market-cap-weighted portfolio.</p><h4>The cost of being different</h4><p>A distinct tilt creates <b>tracking error</b>: the portfolio can behave differently from the broad market, sometimes for years. That difference is not automatically a failure; it is the consequence of owning a different exposure.</p><h4>Portfolio Thesis takeaway</h4><p>Judge a tilt by whether it remains distinct and intentional—not by whether it recently beat the core.</p>`},
multiples:{level:"VALUATION",title:"Valuation Multiples",body:`<p>Valuation multiples compress a relationship between market price and a business measure into a ratio. <b>P/E</b> compares price with earnings, <b>P/B</b> compares price with book value, and <b>EV/EBITDA</b> compares enterprise value with an operating earnings proxy.</p><h4>Useful, but incomplete</h4><p>A lower multiple can mean an asset is inexpensive, or it can reflect weaker growth, lower quality, higher leverage or greater risk. A higher multiple can reflect strong economics—or excessive expectations.</p><h4>Compare like with like</h4><p>Multiples are most informative when compared with the same company's history, a relevant peer group, or a fund's own historical characteristics.</p><h4>Portfolio Thesis takeaway</h4><p>A multiple is evidence about price relative to a financial measure. It is not an intrinsic-value estimate by itself.</p>`},
fcf:{level:"BUSINESS QUALITY",title:"Free Cash Flow",body:`<p><b>Free cash flow (FCF)</b> is the cash generated by operations after capital expenditures. It helps show how much cash remains after the business funds the assets needed to operate and grow.</p><h4>Why cash matters</h4><p>Accounting earnings include non-cash items and estimates. Comparing earnings with cash generation can reveal whether reported profits are translating into cash over time.</p><h4>What companies can do with FCF</h4><p>Free cash flow can be reinvested, used to reduce debt, returned through dividends or repurchases, or accumulated as cash. Capital allocation determines whether those choices create value.</p><h4>Portfolio Thesis takeaway</h4><p>Do not judge FCF from one year alone. Look for durability, conversion from earnings, reinvestment needs and how management deploys the cash.</p>`},
mos:{level:"VALUATION",title:"Margin of Safety",body:`<p>Valuation is an estimate, not a precise fact. A <b>margin of safety</b> compares the current price with an estimated value and shows how much room exists between them.</p><h4>Simple relationship</h4><p><b>Margin of Safety % = (Estimated Value − Price) ÷ Estimated Value × 100</b>.</p><p>If estimated value is $100 and price is $75, the margin of safety is 25%. If price is above estimated value, the result is negative.</p><h4>Scenario discipline</h4><p>Portfolio Thesis separates cautious, normalized and stronger-growth valuation scenarios because changing assumptions can materially change estimated value.</p><h4>Portfolio Thesis takeaway</h4><p>Margin of safety does not eliminate valuation error. It makes the relationship between your assumptions and the market price explicit.</p>`},
volatility:{level:"RISK",title:"Volatility, Drawdowns & Risk",body:`<p><b>Volatility</b> describes how widely returns vary. A <b>drawdown</b> measures the decline from a previous peak to a subsequent trough. Neither measure alone tells you whether an investment thesis is broken.</p><h4>Different kinds of risk</h4><p>Price volatility can be uncomfortable without permanently impairing value. Permanent loss can arise when fundamentals deteriorate, leverage becomes unmanageable, valuation was extreme, or an investor is forced to sell.</p><h4>Portfolio context</h4><p>A volatile 5% sleeve and a volatile 60% core do not create the same portfolio-level risk. Weight and correlation matter alongside the security's own behavior.</p><h4>Portfolio Thesis takeaway</h4><p>Use risk measures to understand the range and source of outcomes, then test whether the underlying thesis changed.</p>`},
rebalancing:{level:"PORTFOLIO MANAGEMENT",title:"Rebalancing",body:`<p>Rebalancing restores a portfolio toward its intended allocation after market movements or contributions change the weights.</p><h4>Maintenance, not prediction</h4><p>A rules-based rebalance does not require forecasting which asset will perform best next. It is a way to keep actual exposures aligned with the portfolio design.</p><h4>Trade-offs</h4><p>Rebalancing too frequently can create unnecessary taxes, spreads or trading. Rebalancing too rarely can allow a winning sleeve to become an unintended concentration. New contributions can sometimes move weights toward target without selling.</p><h4>Portfolio Thesis takeaway</h4><p>Start with the target role and weight. Rebalance because the portfolio drifted from its design—not because recent price movement feels uncomfortable.</p>`},
contribution:{level:"PERFORMANCE",title:"Return vs. Portfolio Contribution",body:`<p>A holding's return tells you how that holding performed. <b>Portfolio contribution</b> estimates how much that performance affected the entire portfolio after accounting for allocation.</p><h4>The basic calculation</h4><p><b>Contribution ≈ Holding Weight × Holding Return.</b> A 60% holding returning −1% contributes about −0.60 percentage points. A 10% holding returning −5% contributes about −0.50 points.</p><h4>Why this changes the story</h4><p>The smaller holding had the much worse return, yet its effect on the portfolio was similar because its allocation was much smaller. This is why Portfolio Thesis shows both security performance and portfolio impact.</p><h4>Portfolio Thesis takeaway</h4><p>Ask two questions: “How did the holding perform?” and “How much did that matter to my portfolio?” They are not the same question.</p>`}
};
let PT_ACADEMY_CACHE=JSON.parse(localStorage.getItem("pt_academy_progress")||"{}");
function academyDone(){return PT_ACADEMY_CACHE;}
function paintAcademy(){const d=academyDone();document.querySelectorAll(".lesson[data-lesson]").forEach(x=>x.classList.toggle("lesson-done",!!d[x.dataset.lesson]));}
function openLesson(id){const l=ACADEMY_LESSONS[id];if(!l)return;document.querySelector("#academy .library").style.display="none";const nav=document.getElementById("lessonNav");if(nav)nav.classList.add("show");const v=document.getElementById("lessonView");v.classList.add("show");document.getElementById("lessonContent").innerHTML=`<h3>${l.title}</h3><div class="lessonbody">${l.body}</div><button class="btn" style="margin-top:18px" onclick="completeLesson('${id}')">${academyDone()[id]?"Completed ✓":"Complete Lesson"}</button>`;if(nav)nav.scrollIntoView({behavior:"smooth",block:"start"});else v.scrollIntoView({behavior:"smooth",block:"start"});}
function closeLesson(){document.getElementById("lessonView").classList.remove("show");const nav=document.getElementById("lessonNav");if(nav)nav.classList.remove("show");document.querySelector("#academy .library").style.display="grid";document.getElementById("academy").scrollIntoView({behavior:"smooth",block:"start"});paintAcademy();}
async function completeLesson(id){
  const now=new Date().toISOString();
  PT_ACADEMY_CACHE[id]={completed:true,completedAt:now};
  localStorage.setItem("pt_academy_progress",JSON.stringify(PT_ACADEMY_CACHE));
  paintAcademy(); openLesson(id);
  if(!window.ptSupabase||!window.ptUser){return;}
  const {error}=await window.ptSupabase.from("academy_progress").upsert(
    {user_id:window.ptUser.id,lesson_slug:id,completed:true,completed_at:now},
    {onConflict:"user_id,lesson_slug"}
  );
  if(error) console.error("Academy sync failed:",error.message);
}
async function loadAcademyProgress(){
  if(!window.ptSupabase||!window.ptUser){paintAcademy();return;}
  const {data,error}=await window.ptSupabase.from("academy_progress").select("lesson_slug,completed,completed_at").eq("user_id",window.ptUser.id);
  if(error){console.error(error.message);return;}
  PT_ACADEMY_CACHE={};
  (data||[]).forEach(r=>{if(r.completed)PT_ACADEMY_CACHE[r.lesson_slug]={completed:true,completedAt:r.completed_at};});
  localStorage.setItem("pt_academy_progress",JSON.stringify(PT_ACADEMY_CACHE)); paintAcademy();
}
document.addEventListener("DOMContentLoaded",paintAcademy);

function showJoinStatus(){
  alert("Membership checkout is not live yet. Account creation and member progress are working; payment checkout will be connected before launch.");
}
const PT_STORAGE_VERSION="v24";
const PT_SUPABASE_URL="https://ngsdgtglfpsnylduivzz.supabase.co";
const PT_SUPABASE_KEY="sb_publishable_SajMQCfHAgR3gpnXXH57SQ_DhmNJUex";
window.ptSupabase=window.supabase.createClient(PT_SUPABASE_URL,PT_SUPABASE_KEY);
window.ptUser=null;

function accountPanel(){
  let p=document.getElementById("ptAccountPanel");
  if(!p){
    p=document.createElement("div");p.id="ptAccountPanel";
    p.style.cssText="position:fixed;inset:0;background:#0009;z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px";
    p.innerHTML=`<div style="background:white;color:#101914;max-width:430px;width:100%;padding:24px;border-radius:16px">
      <div style="display:flex;justify-content:space-between;align-items:center"><h3 style="margin:0">Portfolio Thesis Account</h3><button onclick="document.getElementById('ptAccountPanel').remove()" style="border:0;background:none;font-size:24px">×</button></div>
      <p id="ptAuthStatus" class="muted">Sign in to sync Academy progress across devices.</p>
      <input id="ptEmail" type="email" placeholder="Email" style="width:100%;padding:12px;margin:6px 0;border:1px solid #ccd4cf;border-radius:8px">
      <input id="ptPassword" type="password" placeholder="Password" style="width:100%;padding:12px;margin:6px 0 12px;border:1px solid #ccd4cf;border-radius:8px">
      <div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" onclick="ptSignIn()">Sign In</button><button class="btn outline" onclick="ptSignUp()">Create Account</button><button id="ptLoadPortfolioBtn" class="btn outline" style="display:none" onclick="loadMyPortfolio()">Load My Portfolio</button><button id="ptSignOutBtn" class="btn outline" style="display:none" onclick="ptSignOut()">Sign Out</button></div>
      <div id="ptAuthMsg" style="font-size:13px;margin-top:12px"></div>
    </div>`;
    document.body.appendChild(p);
  }
  refreshAuthPanel();
}
function showAccountInfo(){accountPanel();}
function authMsg(t,bad=false){const e=document.getElementById("ptAuthMsg");if(e){e.textContent=t;e.style.color=bad?"#a22":"#176b4b";}}
async function ensureProfile(user){
  if(!user)return;
  const {error}=await window.ptSupabase.from("profiles").upsert({id:user.id,email:user.email},{onConflict:"id"});
  if(error)console.error("Profile sync:",error.message);
}
async function ptSignUp(){
  const email=document.getElementById("ptEmail").value.trim(), password=document.getElementById("ptPassword").value;
  if(!email||password.length<6){authMsg("Enter an email and a password of at least 6 characters.",true);return;}
  const {data,error}=await window.ptSupabase.auth.signUp({email,password});
  if(error){authMsg(error.message,true);return;}
  if(data.user)await ensureProfile(data.user);
  authMsg(data.session?"Account created and signed in.":"Account created. Check your email if confirmation is required.");
  await syncAuthState();
}
async function ptSignIn(){
  const email=document.getElementById("ptEmail").value.trim(), password=document.getElementById("ptPassword").value;
  const {data,error}=await window.ptSupabase.auth.signInWithPassword({email,password});
  if(error){authMsg(error.message,true);return;}
  await ensureProfile(data.user); authMsg("Signed in. Academy progress is syncing."); await syncAuthState();
}
async function ptSignOut(){await window.ptSupabase.auth.signOut();window.ptUser=null;await syncAuthState();authMsg("Signed out.");}
async function syncAuthState(){
  const {data}=await window.ptSupabase.auth.getUser();window.ptUser=data?.user||null;
  const txt=document.getElementById("accountText");
  if(txt)txt.textContent=window.ptUser?("Signed in • "+window.ptUser.email):"Local prototype mode • sign in to sync";
  const ah=document.getElementById("headerAccount");if(ah){ah.classList.toggle("signed",!!window.ptUser);ah.title=window.ptUser?("Signed in as "+window.ptUser.email):"Sign in or create account";}
  refreshAuthPanel(); await loadAcademyProgress();
  const lib=document.getElementById("library");
  if(lib && getComputedStyle(lib).display!=="none" && typeof ptRefreshLibrary==="function"){
    await ptRefreshLibrary();
  }
}
function refreshAuthPanel(){
  const s=document.getElementById("ptAuthStatus"),o=document.getElementById("ptSignOutBtn"),l=document.getElementById("ptLoadPortfolioBtn");
  if(s)s.textContent=window.ptUser?("Signed in as "+window.ptUser.email):"Sign in to sync Academy progress across devices.";
  if(o)o.style.display=window.ptUser?"inline-block":"none";
  if(l)l.style.display=window.ptUser?"inline-block":"none";
}
document.addEventListener("DOMContentLoaded",async()=>{
  const b=document.getElementById("accountBar");if(b)b.classList.add("show");
  await syncAuthState();
  window.ptSupabase.auth.onAuthStateChange(()=>setTimeout(syncAuthState,0));
});

function ptAuditNavigation(){
  const report=[];
  document.querySelectorAll("a").forEach(a=>{
    const href=a.getAttribute("href")||"";
    if(href.startsWith("#") && href.length>1 && !document.querySelector(href)){
      report.push({text:a.textContent.trim(),href,status:"missing target"});
    }
  });
  if(report.length) console.warn("Portfolio Thesis navigation audit",report);
  else console.info("Portfolio Thesis navigation audit: all internal anchor targets resolve.");
  return report;
}
document.addEventListener("DOMContentLoaded",ptAuditNavigation);
document.addEventListener("DOMContentLoaded",()=>{renderWatchlist();renderDVRanking();});


/* ===== ORIGINAL SCRIPT BLOCK SEPARATOR ===== */


